version: '3.7'

services:
  mongodb:
    image: mongo:latest
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_ROOT_DATABASE: prompt-analyzer
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb-data:/data/db
      - mongodb-log:/var/log/mongodb
  web:
    image: nginx
    volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
    - ./frontend/build:/usr/share/nginx/html
    ports:
    - "8080:80"
volumes:
  mongodb-data:
    driver: local
  mongodb-log:
    driver: local